# Generated by Django 3.2.7 on 2021-09-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_alter_tasks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='types',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Normal', 'Normal')], default='Normal', max_length=100),
        ),
    ]
